version: "3.9.6"

services:
 app:
  container_name: elt_app
  build:
   context: .
  ports:
  - 8000:5000
  volumes:
  - ./:/app
  environment:
    DATABASE_URL: postgresql://postgres:example@db:5432/postgres
  depends_on:
   - db

 db:
  container_name: etl_db
  image: postgres
  restart: always
  ports:
   - 5432:5432
  environment:
    POSTGRES_PASSWORD: example
