"""empty message

Revision ID: 7b10b5f552a7
Revises: 
Create Date: 2023-06-01 22:25:22.575138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b10b5f552a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('average_experiments', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('signup_date', sa.Date(), nullable=True),
    sa.Column('total_experiments', sa.Integer(), nullable=True),
    sa.Column('most_common_compound_name', sa.String(length=128), nullable=True),
    sa.Column('most_common_compound_structure', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('global_statistics')
    # ### end Alembic commands ###
